language: ruby
rvm:
  - 2.2.0
script: ./create.sh
after_success: ./update-gh-pages.sh
env:
  global:
  - secure: hICrH7fr6dVqTKfQBs0/2A811dmZQaHQADHtLdEDrBddeHBTIP1CM2nvCvG8nHbRYxqT+xjoei8kdS8UcqHP6INthIqUZAMcNnfZB8WgsJ55nN/9cuCCYs284Pge7T+9LzB9epEN4tji4Qf/D0ICMr+2kIbubJkdtuqoDU8a1CBfPxf8c+Le9H8LQMjAvYnmgmar/ILY2fBHeWyVoe8MihHICDCFV22zrfUdUF4KGLqiFc228J/yRXB3xddchyZoU8ACbq3v/C8TmKSxIHMQTB+qiT7gUpY+QTZ4nXpH7yohvXwX0YogQEypTuzTQK/6HMPg0110nphwiHQM7kYtRuCGi0QmTrbBQkUt3UIoKMnjOrLIhCZW4LsRvgpiofVwsSGR1/WD535F68fmlU5K5JWgjPYC7pZF+JaM9AKPRImpmsH+xrXyQRoYnKaYCqI3ln14f5+V/aRh93HfMMYn39aE9Bsg5Ob+PFXrjpTphungFr5FhymAPoDAvgL6IoRwz07zhNsJ7cTWm6S+fH4a+0URIk/vedoIwoXb7uMn2a/NnHtCEuUo4KwbCpU8wfRIPhJLy9cyw1HyVaAiQzlPN8sb3kUwuTe7y51VjG8Gnn6rXyhOzBlfca+u3a20plic2fWlGsriaFebfK7K18u//C8eEhvhIKUUh6P9MFWAnN4=
